### ISSUE TITLE
redis.v3: how to get set options out of the database

### ISSUE THREAD

**Issue by sztanpet** [tideland/godm#2]
There is a way to set options, but there is not a way to get the options that were set, I think it should be symmetrical.

Granted it is easy to "work around" this since I already know the database number I set for example, so  not particularly a big deal if you should refuse this feature.

Maybe something like `GetIndex(*Db) int`?
Thanks for considering!

**Comment by TheMue** [comment]
Sounds reasonable, yes. Will think about how to implement it best.

**Comment by sztanpet** [comment]
the particular reason I am asking for this is because I have a little helper function for setting up subscriptions, these are not local to the particular selected db, so I include the db number in the channel name (cn in the snippet) to support running a dev environment on the same db as the live one (I could just as easily pass it in an argument)


    func SetupSubscribe(db *redis.Database, cn string, cb func(*redis.PublishedValue)) {
    again:
      sub, err := db.Subscription()
      if err != nil {
        goto again
      }

      n := redis.GetIndex(db) // no such thing
      err = sub.Subscribe(fmt.Sprintf("%s-%d", cn, n))
      if err != nil {
        goto again
      }

      for {
        result, err := sub.Pop()
        if err != nil {
          goto again
        }

        if result.Value.IsNil() {
          continue
        }

        cb(result)
      }
    }

**Comment by TheMue** [comment]
You can retrieve the configuration now using `db.Options()`. It returns a struct containing all configuration data. See https://godoc.org/github.com/tideland/godm/v3/redis#Database.Options

**Comment by sztanpet** [comment]
thank you!
